# @package _global_
agent:
  dyn:
    _target_: nets.DynConcat
    params:
      n: ${train.n_hist_frames}  # This dynamics model can only work with a certain number of previous frames
      nobj: ${agent.nobj}