# @package _global_
agent:
  dyn:
    _target_: nets.DynSTN
    params:
      n: ${train.n_hist_frames}  # This dynamics model can only work with a certain number of previous frames
      nobj: ${agent.nobj}
      num_tx: 16
      base_stn: ${agent.base_stn}