# @package _global_
agent:
  dyn:
    _target_: nets.DynSTNPixelChannels
    params:
      n: ${train.n_hist_frames}  # This dynamics model can only work with a certain number of previous frames
      nobj: ${agent.nobj}
      base_stn: ${agent.base_stn}