# @package _global_
agent:
  obj_fwd:
    _target_: obj_nets.TemporalInteractionNetwork
    params:
      hist_frames: ${agent.model_hist_frames}
      only_pred_dynamic: True
      clip_output: True
      dont_predict_ball_theta_v: True
      position_invariant: False